"""seasons and Game.season_id

Revision ID: ce35d2462b89
Revises: eb1ea2a3ea8c
Create Date: 2023-04-04 00:42:27.645972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce35d2462b89'
down_revision = 'eb1ea2a3ea8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.Integer(), server_default="1", nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_games_season_id_seasons'), 'seasons', ['season_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_teams_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_teams_name'), type_='unique')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_season_id_seasons'), type_='foreignkey')
        batch_op.drop_column('season_id')

    op.drop_table('seasons')
    # ### end Alembic commands ###
